### ISSUE TITLE
VRCUrl edit string!!!

### ISSUE THREAD

**Issue by denis-hik** [vrchat-community/UdonSharp#115]
VRCUrl(string url) | Constructor that takes a URL as input. Note that this can only be called at editor time.

Pls, add feature on edit VRCUrl in Udon program !!

**Comment by jellejurre** [comment]
Creating vrcurl at runtime being disabled is a security feature IIRC

**Comment by MerlinVR** [comment]
U# does not have control over this. Udon doesn't expose the constructor at runtime. Here is the canny for this https://feedback.vrchat.com/vrchat-udon-closed-alpha-feedback/p/allow-construction-of-vrcurl-at-runtime
