### ISSUE TITLE
0Harmony.dll should not be included in the VPM package.

### ISSUE THREAD

**Issue by uhKayla** [vrchat-community/UdonSharp#129]
**Describe the bug in detail:**
Including 0Harmony.dll in the main package will automatically break other harmony-dependent packages, when Harmony is installed manually or from a specific Harmony VPM package. This should be changed to install as a dependent package from a registry, while checking for Harmony on import.

**Provide steps/code to reproduce the bug:**
Import UdonSharp using VRCC in any project already using Harmony, such as [RATS](https://github.com/rrazgriz/RATS)

**Expected behavior:**
UdonSharp should check for Harmony on import.

**Additional Information:**
Console errors with conflicting dependencies *will clear* when requested, therefore this issue is easy to miss, and can be complicated to track down.

**Comment by rrazgriz** [comment]
I think a better solution would be providing it as an official dependency through VCC, so other packages can depend on it: https://github.com/vrchat-community/creator-companion/issues/75

**Comment by rrazgriz** [comment]
`com.vrchat.base` 3.4.0 now bundles Harmony, which smooths handling of the Harmony dependency: https://github.com/vrchat-community/creator-companion/issues/75#issuecomment-1751513947
