### ISSUE TITLE
Udon ignore compile constant

### ISSUE THREAD

**Issue by CorneliusCornbread** [vrchat-community/UdonSharp#21]
Compile time constant (ex `UDON_COMPILE`) that is false only when udon compiles the script/ignores everything inside the `#if` compile check.

I'm trying to make use of some MyBox attributes to make sorting things in the inspector easier and being able to use them while Udon doesn't throw a fit would be nice.

**Comment by MerlinVR** [comment]
This is currently provided by the `COMPILER_UDONSHARP` constant which is only true when code is being compiled by UdonSharp.
