### ISSUE TITLE
Proxy function to handle prefab modifications

### ISSUE THREAD

**Issue by BocuD** [vrchat-community/UdonSharp#23]
**Feature Description:**
This would be a function on the base UdonSharpBehaviour class that checks if the gameobject the target behaviour is on is part of any prefab, and if yes, records prefab instance modifications for the behaviour. It could speed up adding proper prefab support to custom inspectors and editor scripts.

**Additional context:**
For example something like this:
```cs
public void HandlePrefabModifications()
{
    if (PrefabUtility.IsPartOfAnyPrefab(gameObject))
    {
        EditorUtility.SetDirty(this);
        PrefabUtility.RecordPrefabInstancePropertyModifications(this);
    }
}
```
In the custom inspector, you could then simply do
```cs
EditorGUI.BeginChangeCheck();
someBehaviour.someStringProperty = EditorGUILayout.TextField("String property: ", someBehaviour.stringProperty);
if (EditorGUI.EndChangeCheck())
{
    someBehaviour.HandlePrefabModifications();
}
```

**Comment by MerlinVR** [comment]
Discussed on Discord for context: https://discord.com/channels/652715801714884620/690799234991259708/956270013835255808
