### ISSUE TITLE
Udonsharp Editor Error

### ISSUE THREAD

**Issue by CrazylTrain** [vrchat-community/UdonSharp#3]
**Describe the bug in detail:**
So the main Error I have been getting in Unity, when trying to put a new media player in, is something to do with Udon Sharp Editor, now its CsSharp, and some other things

**Provide steps/code to reproduce the bug:**
Just trying to add a Media player, Pro TV v 2.2 lastest update into the Suburban Lakehouse Package.

![image](https://user-images.githubusercontent.com/98568045/151479677-f0f50993-d6a5-4a82-8d4f-9e5a7de581f8.png)
![image](https://user-images.githubusercontent.com/98568045/151479715-ebfca80e-492b-40ea-b32c-56319d05f60a.png)
![image](https://user-images.githubusercontent.com/98568045/151479767-d72b609b-ec8c-4f42-89cb-33a8a0078c09.png)

**Comment by MerlinVR** [comment]
Follow the installation instructions, you need to use the unitypackage https://github.com/vrchat-community/UdonSharp#installation
