### ISSUE TITLE
No release unitypackage is available on the new repository

### ISSUE THREAD

**Issue by bdonlan** [vrchat-community/UdonSharp#4]
**Describe the bug in detail:**
There is no unitypackage in this repository's releases tab.

**Provide steps/code to reproduce the bug:**
Go to https://github.com/vrchat-community/UdonSharp/releases

**Expected behavior:**
The latest stable version of U# should be available as a unitypackage

**Additional Information:**
While they're still available at the old repository, having the old releases only available in the old repo is likely to lead to confusion.

**Comment by XomiashVR** [comment]
Click on tags, all the releases are there.

https://github.com/vrchat-community/UdonSharp/tags

**Comment by PhaxeNor** [comment]
They are just copies of the repo at the given time a release was pushed. Not something you'd want to extract in your project unless you know what you're doing.

BD is talking about a proper release package that only has the needed files and folders

**Comment by XomiashVR** [comment]
Ignore me I just being blind, thought there were releases there as well.

**Comment by MerlinVR** [comment]
Now mirrored to https://github.com/vrchat-community/UdonSharp/releases thanks!
