### ISSUE TITLE
[1.0.0 | 1.0.1] OnPlayerTriggerEnter does not work

### ISSUE THREAD

**Issue by Janooba** [vrchat-community/UdonSharp#42]
**Describe the bug in detail:**
OnPlayerTriggerEnter Exit etc do not work. They don't trigger anything. OnTriggerEnter triggers fine.

**Provide steps/code to reproduce the bug:**
- Create new project using U# 1.0.1 or 1.0.0
- Create basic scene to walk around in and add
    - a gameobject with a box collider set to trigger
    - a rigidbody set to kinematic
    - a new U# script
- In the U# script, override OnPlayerTriggerEnter and add a debug.log (or activate/deactivate a gameobject for build testing)
- Play or build and walk into the trigger
- No Debug log is sent to console / trigger isn't triggered

**Expected behavior:**
OnPlayerTriggerEnter should trigger when players enter a collider set to trigger on the same or child objects

**Additional Information:**
I can provide a repro project if needed, but it's not a complex setup.

**Comment by MerlinVR** [comment]
Cannot repro in Build & Test

![image](https://user-images.githubusercontent.com/36685500/172772035-853ff893-78d5-49fa-8a30-597bd1dc94a0.png)
![image](https://user-images.githubusercontent.com/36685500/172771915-7233e625-6004-48e7-b015-1e4a262f063a.png)

![image](https://user-images.githubusercontent.com/36685500/172771848-106a99ba-08f8-4e30-8dd3-39e7c72e7a7e.png)

**Comment by Janooba** [comment]
Will getcha a repro if I can :)

**Comment by Janooba** [comment]
Looks like it was an issue with how I had the rigidbodies set up. There was an extra one on a child somewhere. Looks like there's no issue after all.
I appreciate your quick response!
