### ISSUE TITLE
UnityEditor Crash by UdonSharp compile

### ISSUE THREAD

**Issue by oOtroyOo** [vrchat-community/UdonSharp#44]
**Describe the bug in detail:**
![2022-06-12 231519](https://user-images.githubusercontent.com/19978148/173240210-97de2745-ee53-4196-9d07-e4a83dd799cd.jpg)

I'm not sure why .
I guess compiling  `string + property` has some bug.
 but when i use `string.format` to replace that code ,it will fix the problem.

**Comment by MerlinVR** [comment]
Cannot repro, is this happening when the script runs in play mode? Please post the output log that Unity makes, and if possible a minimal script that causes the issue.

**Comment by MerlinVR** [comment]
Also forgot to confirm, is this in U# 1.0?
