### ISSUE TITLE
"!>" (not greater than) generates exception not caught by UdonSharp

### ISSUE THREAD

**Issue by DarkSpacer1** [vrchat-community/UdonSharp#5]
This line of code: if (otherNeso.isPanicing && Vector3.Distance(transform.position, otherNeso.transform.position) < 0.4 && interactionType != 3 && interactionStep !> 0)

THe last comparison in this if statement generates an exception:  Apparently !> is not a symbol recognized by UdonSharp.  This generates an unhelpfull error: Error: Could not load signature of VRC.SDK3.Components.MultipleDisplayUtilities:GetRelativeMousePositionForDrag due to: Could not load file or assembly 'UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:<unknown type> member:(null) signature:<none>

It seems that this symbol is not a standard operator, but the errors generated by its use are very unhelpful.  It could be good to insert at least some sort of error message...I spent a few days trying to figure out what the heck was going on >_<

**Comment by MerlinVR** [comment]
This is a Unity error when loading assemblies and has no bearing on U# as far as I am aware.

**Comment by DarkSpacer1** [comment]
What I was trying to say was the error fell through UdonSharp entirely and landed on UnityEngine.UI.

**Comment by MerlinVR** [comment]
That is a syntax error and shows up fine for me in compiles as expected, make sure you aren't hiding errors in the console.
![image](https://user-images.githubusercontent.com/36685500/152887231-42142127-96aa-4b9c-920f-f54ed6865f88.png)
![image](https://user-images.githubusercontent.com/36685500/152887247-2e1b6802-33b9-45f0-a838-ce179552ef77.png)

**Comment by DarkSpacer1** [comment]
That's interesting.  Visual Studio Code doesn't seem to mark it as bad syntax...

**Comment by MerlinVR** [comment]
Generally VS code's C# support for Unity is pretty lacking. I'd suggest Visual Studio, or if you can pay for it, Rider is absolutely worth it.

**Comment by DarkSpacer1** [comment]
I've never really run into anything like this error with VSCode before and I'm been doing some advanced things with U#.  In this case I can just use "==" instead anyway
