### ISSUE TITLE
2D arrays are no longer displayed in inspector.

### ISSUE THREAD

**Issue by noritama-vrc** [vrchat-community/UdonSharp#57]
**Describe the bug in detail:**
Previously, 2D arrays with public or [SerializeField] attributes were displayed in inspector in UdonSharp, but they are no longer displayed in UdonSharp now.

Image 1:Code
![スクリーンショット (370)](https://user-images.githubusercontent.com/91783406/185729641-42eb06e8-759d-4751-ae82-e20ba1646569.png)

Image 2:inspector of v0.20.3
![スクリーンショット (371)](https://user-images.githubusercontent.com/91783406/185729642-13e13a32-69a9-4148-97d5-b304c55e9e5e.png)

Image 3: inspector of v1.0.0b9
![スクリーンショット (372)](https://user-images.githubusercontent.com/91783406/185729648-211e015b-2b5c-4e58-8911-10a9aa54d6df.png)

**Provide steps/code to reproduce the bug:**
1. Descrive 2D arrays with public or [SerializeField] attributes and attache to UdonBehaviour
2. See Inspector(always occuer)

**Expected behavior:**
2D arrays should be display in inspector.
The Udon gimmick that allows users to set parameters in a 2D array is no longer available, and should be fixed.

**Additional Information:**
I wrote same issue in VRChat canny.
https://feedback.vrchat.com/vrchat-udon-closed-alpha-bugs/p/2d-arrays-are-no-longer-displayed-in-inspector

**Comment by MerlinVR** [comment]
This is intentional as they wouldn't serialize with just `[SerializeField]` anymore due to Unity's serializer not handling jagged arrays. If you mark the fields with `[OdinSerialize]` instead they should still show up in 1.0. They will show up at the bottom of the inspector list due to how compatibility is handled.
