### ISSUE TITLE
Expose method summary text

### ISSUE THREAD

**Issue by StrikerUnit** [vrchat-community/UdonSharp#93]
UdonSharp 1.1.6

**Feature Description:**
Hi, I just starting using UdonSharp. Not sure why the method summary text is not exposed like in the https://udonsharp.docs.vrchat.com/vrchat-api

![image](https://user-images.githubusercontent.com/21314944/210130126-d85bc2fe-e2b0-4349-8bbd-29bce581f713.png)
![image](https://user-images.githubusercontent.com/21314944/210130136-5beed886-3d43-41bf-95ec-ee422ab32fb2.png)

compare to method from unity:
![image](https://user-images.githubusercontent.com/21314944/210130145-be6dae7f-51db-4d9e-8fa0-18b033e15d39.png)
![image](https://user-images.githubusercontent.com/21314944/210130152-97f918ad-943d-451d-8aa7-1298aef9d456.png)

**Comment by MerlinVR** [comment]
Hi, this is not something U# can do for SDK libraries, here is the relevant canny: https://vrchat.canny.io/vrchat-udon-closed-alpha-feedback/p/documentation-for-sdk-libraries 

U# already documents most of the commonly used APIs that it defines, see UdonSharpBehaviour.cs for reference.
