### ISSUE TITLE
Export to Assembly Asset is missing.

### ISSUE THREAD

**Issue by Fairpl3x** [vrchat-community/UdonSharp#99]
Previously with U# 0.20.x it was possible to export to an Assembly Asset according to this Wiki:

https://github.com/vrchat-community/UdonSharp/wiki/Exporting-to-Assembly-Files

The button is gone and trying to manually copy paste a compiled assembly will throw an exception.

![Screenshot_3](https://user-images.githubusercontent.com/31825109/214860198-102b54d3-2797-425b-9c39-074a8127b980.png)

**Comment by MerlinVR** [comment]
This functionality does not exist in 1.0 because it doesn't work with U#'s runtime model, and won't work at all with Udon 2 due to not compiling to uasm.
